initial docker build
linuxserver/docker-paperless-ng pull request #1
Opened 2021-07-10 12:56 UTC by alex-phillips

2021-07-11 14:15 UTC, TheSpad commented
Build still failing, looks like scipy needs `gfortran` to compile.

2021-07-13 21:00 UTC, Roxedus requested changes

2021-07-14 13:17 UTC, alex-phillips commented on root/etc/services.d/paperless/run
> +	s6-setuidgid abc /usr/bin/uwsgi uwsgi.ini
Copy/paste errors. I feel so ashamed. I hope you don't think I _normally_ use tabs...

2021-07-14 18:05 UTC, Roxedus approved these changes

2021-07-14 18:12 UTC, Roxedus commented
Related PR: https://github.com/linuxserver/cstate/pull/38

2021-07-19 14:40 UTC, merged